In [25]:
import pandas as pd
import numpy as np
from pathlib import Path

In [26]:
proj_dir = Path.cwd().parent
raw_data_dir = proj_dir/"data"/"raw"

In [27]:
csv_file = sorted(raw_data_dir.rglob("*.csv"))


df = pd.read_csv(csv_file[0],
                low_memory=False,
                parse_dates=["started_at","ended_at"],
                dtype={
                    "start_station_name": "string",    
                    "start_station_id": "string",         
                    "end_station_name": "string",
                    "end_station_id":"string"          
                })

df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8E865410DBDE0CA9,electric_bike,2024-01-01 13:00:04.563,2024-01-01 13:04:04.652,3 St & 3 Ave,4028.03,Carroll St & Smith St,4225.14,40.675070,-73.987752,40.680611,-73.994758,casual
1,0403D0B3FC9CA77D,electric_bike,2024-01-08 19:36:43.520,2024-01-08 19:53:16.266,Franklin Ave & St Marks Ave,4107.05,Bedford Ave & Bergen St,4066.15,40.675832,-73.956168,40.676368,-73.952918,casual
2,F6DE7BB42FF550BE,electric_bike,2024-01-12 15:00:41.580,2024-01-12 15:36:29.622,W 67 St & Broadway,7116.04,Central Park W & W 103 St,7577.27,40.774925,-73.982666,40.795590,-73.961884,casual
3,84A995BFD98030D4,classic_bike,2024-01-12 16:52:19.025,2024-01-12 17:17:29.773,Central Park West & W 68 St,7079.06,E 5 St & Ave C,5545.04,40.773407,-73.977825,40.722992,-73.979955,member
4,7BBEAD4F2B535813,electric_bike,2024-01-05 19:50:19.202,2024-01-05 20:34:42.517,W 67 St & Broadway,7116.04,Ave A & E 14 St,5779.11,40.774925,-73.982666,40.730311,-73.980472,member

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1000000 non-null  str
 1   rideable_type       1000000 non-null  str
 2   started_at          1000000 non-null  datetime64[us]
 3   ended_at            1000000 non-null  datetime64[us]
 4   start_station_name  999424 non-null   string
 5   start_station_id    999424 non-null   string
 6   end_station_name    996936 non-null   string
 7   end_station_id      996936 non-null   string
 8   start_lat           999424 non-null   float64
 9   start_lng           999424 non-null   float64
 10  end_lat             996948 non-null   float64
 11  end_lng             996948 non-null   float64
 12  member_casual       1000000 non-null  str
dtypes: datetime64[us](2), float64(4), str(3), string(4)
memory usage: 183.8 MB

In [29]:
df.isna().sum()

ride_id                  0
rideable_type            0
started_at               0
ended_at                 0
start_station_name     576
start_station_id       576
end_station_name      3064
end_station_id        3064
start_lat              576
start_lng              576
end_lat               3052
end_lng               3052
member_casual            0
dtype: int64

In [30]:
df[df["start_station_id"].isna()].head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
3687,D3E87CC64811E675,electric_bike,2024-01-13 08:49:15.112,2024-01-13 08:55:37.060,<NA>,<NA>,Grand Ave & 55 St,5369.01,NaN,NaN,40.718880,-73.914270,casual
15447,3E9DB8E8457C831D,electric_bike,2024-01-06 12:16:40.224,2024-01-06 12:21:45.707,<NA>,<NA>,Albany St & Greenwich St,5145.02,NaN,NaN,40.709267,-74.013247,member
16000,44FEC50C562E94E1,electric_bike,2024-01-02 16:15:46.139,2024-01-02 16:25:02.413,<NA>,<NA>,5 Ave & E 30 St,6248.08,NaN,NaN,40.745985,-73.986295,member
19299,78DF25A840C62EEB,electric_bike,2024-01-02 18:45:58.448,2024-01-02 19:09:14.671,<NA>,<NA>,Broadway & W 38 St,6560.15,NaN,NaN,40.752973,-73.987349,casual
21094,DC097C859372FA64,electric_bike,2024-01-06 17:33:28.919,2024-01-06 17:38:07.327,<NA>,<NA>,Fulton St & Irving Pl,4263.12,NaN,NaN,40.681860,-73.959432,member

In [31]:
df.loc[df["start_station_id"].isna(), "rideable_type"].value_counts()

rideable_type
electric_bike    576
Name: count, dtype: int64

In [32]:
df.loc[df["end_station_id"].isna(), "rideable_type"].value_counts()

rideable_type
electric_bike    2762
classic_bike      302
Name: count, dtype: int64

In [33]:
df.loc[df["start_station_id"].isna() & df["end_station_id"].isna()].shape

(240, 13)

In [34]:
df.dropna(subset=["start_station_id","end_station_id"], inplace=True)

In [35]:
df.loc[df["start_station_id"].isna() & df["end_station_id"].isna()].shape

(0, 13)

In [36]:
df["started_at_date"] = df["started_at"].dt.floor("h")
df["started_at_date"].head()

0   2024-01-01 13:00:00
1   2024-01-08 19:00:00
2   2024-01-12 15:00:00
3   2024-01-12 16:00:00
4   2024-01-05 19:00:00
Name: started_at_date, dtype: datetime64[us]